# Generated by Django 6.0.6 on 2026-06-17 04:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caso',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=50, primary_key=True, serialize=False)),
                ('victim_rut', models.CharField(blank=True, default='', max_length=20)),
                ('victim_nombre', models.CharField(blank=True, default='', max_length=100)),
                ('victim_telefono', models.CharField(blank=True, default='', max_length=20)),
                ('victim_contacto_nombre', models.CharField(blank=True, default='', max_length=100)),
                ('victim_contacto_telefono', models.CharField(blank=True, default='', max_length=20)),
                ('contacto_estado', models.CharField(blank=True, choices=[('contactado', 'Contactado'), ('sin_respuesta', 'Sin Respuesta')], max_length=20, null=True)),
                ('contacto_notas', models.TextField(blank=True, default='')),
                ('emergencia', models.JSONField(blank=True, null=True)),
                ('contexto', models.JSONField(blank=True, default=dict)),
                ('estado', models.CharField(choices=[('recibida', 'Recibida'), ('aceptada', 'Aceptada'), ('asignada', 'Asignada'), ('en_terreno', 'En Terreno'), ('completada', 'Completada')], default='recibida', max_length=20)),
                ('asignados', models.JSONField(blank=True, default=list)),
                ('comisaria_cercana', models.CharField(blank=True, default='', max_length=200)),
                ('servicios_externos', models.JSONField(blank=True, default=list)),
                ('nota_operador', models.TextField(blank=True, default='')),
                ('preguntas_terreno_pendientes', models.JSONField(blank=True, default=list)),
                ('respuestas_terreno', models.JSONField(blank=True, default=dict)),
                ('ubicacion_carabinero', models.JSONField(blank=True, default=dict)),
                ('tiempo_estimado_llegada', models.IntegerField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('acta', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, default='', max_length=20)),
                ('direccion', models.TextField(blank=True, default='')),
                ('contacto_nombre', models.CharField(blank=True, default='', max_length=100)),
                ('contacto_telefono', models.CharField(blank=True, default='', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
