# Generated by Django 4.2.30 on 2026-06-17 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='gps_last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caso',
            name='gps_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caso',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caso',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfil',
            name='blocked_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='perfil',
            name='num_documento',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
